services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./css:/usr/share/nginx/html/css
      - ./js:/usr/share/nginx/html/js
      - ./img:/usr/share/nginx/html/img
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf